version: 3.0.1.{build}
image: Visual Studio 2022
# Uncomment following lines to log environment variables
#init:
#- set

branches:
  only:
  - master
  - /V.*/

configuration: Release
platform: Any CPU
build_script:
- cmd: CI
test: off

artifacts:
  - path: 'code\Artifacts\Packages\*.nupkg'
    name: NFluentPackages

environment:
  NFLUENT_NUGET_FEED: https://www.nuget.org/api/v2/package
  CODECOV_KEY:
    secure: DsJzrv6YlrqW177NuquKFS/jq6Cj4PMJ2+QyuY+Garee3M+M+gWhplP0sRKFUIqZ

assembly_info:
  patch: true
  file: version.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

notifications:
- provider: Slack
  incoming_webhook:
    secure: 8HsB7ugtiao2POPBIleKwZhgUm/eXfndfmhRN9ewMr+etPGhsrJ8Wy6jIlqeJAgHlsdVIpaL2TGEEOEuMm9LcZbYP9n8BWw5Nd2vOcsnLO4=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
- provider: GitHubPullRequest
  template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
  auth_token:
      secure: kCICf0+4Cc7GIVkQ072LtcxBKKhynEsSx612WwmUi3NAs8C/14iHy7PlXTUWyyYR9
      